name: Pipeline

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '30 08 * * *'

jobs:
  build:
    name: "Test Tut general"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Run batect test in dev container
        uses: devcontainers/ci@v0.2
        with:    
          # [Optional] If you have a separate workflow like the one above
          # to pre-build your container image, you can reference it here
          # to speed up your application build workflows as well!
          # cacheFrom: ghcr.io/example/example-devcontainer

          push: main
          runCmd: ./batect test
          
  test_basic:
    name: "Test Tut Part 1"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      TAP_GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_KEY_GITHUB }}

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Run batect test in dev container
        uses: devcontainers/ci@v0.2
        with:    
          # [Optional] If you have a separate workflow like the one above
          # to pre-build your container image, you can reference it here
          # to speed up your application build workflows as well!
          # cacheFrom: ghcr.io/example/example-devcontainer

          push: never
          runCmd: ./batect test
  int_test:
    name: "Test Tut Part 2"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      TAP_GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_KEY_GITHUB }}

    steps:
      - uses: actions/checkout@v3.2.0
      
      - name: Run batect test_2 (with postgres) in dev container
        uses: devcontainers/ci@v0.2
        with:    
          # [Optional] If you have a separate workflow like the one above
          # to pre-build your container image, you can reference it here
          # to speed up your application build workflows as well!
          # cacheFrom: ghcr.io/example/example-devcontainer

          push: never
          runCmd: ./batect test_2
