name: Pipeline for tutorial testing

on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '30 08 * * *'
  workflow_dispatch:
    tags:
    description: 'Test scenario tags'
    required: false
    type: boolean


jobs:
  build:
    name: "Test meltano install"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Run batect test in dev container
        uses: devcontainers/ci@v0.2
        env:  
          TERM: xterm-256color
          BATECT_CACHE_TYPE: directory
          BATECT_ENABLE_TELEMETRY: true
          TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}
        with:  
          push: never
          runCmd: ./batect test_install 
          env: |
            TERM
            BATECT_CACHE_TYPE
            BATECT_ENABLE_TELEMETRY
            TAP_GITHUB_AUTH_TOKEN


  test_bat:
    name: "Test batect"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Run batect test in dev container
        uses: devcontainers/ci@v0.2
        env:  
          TERM: xterm-256color
          BATECT_CACHE_TYPE: directory
          BATECT_ENABLE_TELEMETRY: true
          TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}
        with:    
          env: |
            TERM
            BATECT_CACHE_TYPE
            BATECT_ENABLE_TELEMETRY
            TAP_GITHUB_AUTH_TOKEN
          push: never
          runCmd: ./batect test_batect

  test_basic:
    name: "Test tap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Run batect test in dev container
        env:  
          TERM: xterm-256color
          BATECT_CACHE_TYPE: directory
          BATECT_ENABLE_TELEMETRY: true
          TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}
        uses: devcontainers/ci@v0.2
        with:    
          env: |
            TERM
            BATECT_CACHE_TYPE
            BATECT_ENABLE_TELEMETRY
            TAP_GITHUB_AUTH_TOKEN
          push: never
          runCmd: ./batect test_tap
  int_test:
    name: "Test real tap & target"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      
      - name: Run batect test_2 (with postgres) in dev container
        env:  
          TERM: xterm-256color
          BATECT_CACHE_TYPE: directory
          BATECT_ENABLE_TELEMETRY: true
          TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}
        uses: devcontainers/ci@v0.2
        with:    
          env: |
            TERM
            BATECT_CACHE_TYPE
            BATECT_ENABLE_TELEMETRY
            TAP_GITHUB_AUTH_TOKEN
          push: never
          runCmd: ./batect test_tap_target

  fix_test:
    name: "Test fixed tap & target"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      
      - name: Run batect test_2 (with postgres) in dev container
        env:  
          TERM: xterm-256color
          BATECT_CACHE_TYPE: directory
          BATECT_ENABLE_TELEMETRY: true
          TAP_GITHUB_AUTH_TOKEN: ${{ secrets.TAP_GITHUB_AUTH_TOKEN }}
        uses: devcontainers/ci@v0.2
        with:    
          env: |
            TERM
            BATECT_CACHE_TYPE
            BATECT_ENABLE_TELEMETRY
            TAP_GITHUB_AUTH_TOKEN
          push: never
          runCmd: ./batect test_tap_target_fixed

